### ISSUE TITLE
working demo on github-pages?

### ISSUE THREAD

**Issue by filipbech** [filipbech/element-router#3]

**Comment by filipbech** [comment]
maybe somewhere more SPA-ready... what could that be? firebase-hosting?

**Comment by joegaffey** [comment]
I was playing with it [here](https://glitch.com/edit/#!/element-router).
Had to just make some minor modifications to the package.json.

**Comment by filipbech** [comment]
Thanks @joegaffey ... I put a demo up on a firebase hosting site... https://elementrouter.firebaseapp.com/

What did you need to change?

**Comment by joegaffey** [comment]
Had to add an "engines" section to specify a later node version and changed "serve" script to "start".
Check it out here:
https://glitch.com/edit/#!/element-router?path=package.json:1:0

**Comment by filipbech** [comment]
That looks really cool... way easier to get started from when just playing around... can I link to that one?

**Comment by joegaffey** [comment]
Sure. Let me know if you want to be added as a collaborator.
